name: Node.js CI

on:
  push:
    branches: 
      - "sandeep"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.0'  # Specify the version of Node.js to install

      - name: Install dependencies and run npm command
        working-directory: my-app
        run: |
          npm i
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: my-app/build
          retention-days: 5

      - name: Download a single artifact
        uses: actions/download-artifact@master
        with:
          name: dist

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          script: |
            cd home 
            sudo rm -rf *
            
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html
            sudo rm -rf *
            sudo mv /home/ubuntu/home/my-app/build/* .
