name: Node.js CI

on:
  push:
    branches: [ "sandeep" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.0'  # Specify the version of Node.js to install

      - name: Install dependencies and run npm command
        working-directory: igs-skillviz-fe-feature-qualifications
        run: |
          npm i
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: igs-skillviz-fe-feature-qualifications/dist
          retention-days: 5

      - name: Download a single artifact
        uses: actions/download-artifact@master
        with:
          name: dist

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
        with:
          # SSH command to connect to the server and execute commands
          ssh -i "$SSH_PRIVATE_KEY" "$REMOTE_USER@$REMOTE_HOST" "rm -rf $TARGET/* && exit" 
          SSH_EXIT_CODE=$?
          if [ $SSH_EXIT_CODE -ne 0 ]; then
            echo "SSH command failed with exit code $SSH_EXIT_CODE"
            exit $SSH_EXIT_CODE
          fi

          # SCP command to copy files to the server
          scp -i "$SSH_PRIVATE_KEY" /local/path/file.txt "$REMOTE_USER@$REMOTE_HOST:$TARGET/"
