name: Node.js CI

on:
  push:
    branches: [ "sandeep" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.0'  # Specify the version of Node.js to install

      - name: Install dependencies and run npm command
        working-directory: igs-skillviz-fe-feature-qualifications
        run: |
          npm i
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: igs-skillviz-fe-feature-qualifications/dist
          retention-days: 5

      - name: Download a single artifact
        uses: actions/download-artifact@master
        with:
          name: dist

      - name: SSH SCP SSH Pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          key:  ${{ secrets.DC_key }}
          connect_timeout: 10s
          first_ssh: |
            rm -rf /var/www/html
            ls -la
            echo $WELCOME 
          scp: |
            './/home/sandeep/goac-sandeep/igs-skillviz-fe-feature-qualifications/dist/*' => /var/www/html/
           
