name: Node.js CI

on:
  push:
    branches: [ "sandeep" ]
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
           node-version: '20.12.0'  # Specify the version of Node.js to install
      - name: Install depandencies and run npm command
        working-directory: igs-skillviz-fe-feature-qualifications
        run: |
          npm install
          npm run build

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: /dist
          retention-days: 5

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: SSH commands delete the older files and upload the files
        shell: bash
        run: |
          ssh -i /home/sandeep/goac-sandeep/goac-sandeep.pem ubuntu@ec2-13-232-52-59.ap-south-1.compute.amazonaws.com 'echo "Deleting existing files in remote directory..." && sudo rm -rf ${{ inputs.remote-directory }}/*'
          ssh -i /home/sandeep/goac-sandeep/goac-sandeep.pem ubuntu@ec2-13-232-52-59.ap-south-1.compute.amazonaws.com 'echo "Deploying files to server..."'
          rsync -avz --delete "${{ inputs.local-directory }}"/* -e "ssh -i /home/sandeep/goac-sandeep/goac-sandeep.pem" ubuntu@ec2-13-232-52-59.ap-south-1.compute.amazonaws.com:/var/www/html/

      - name: SSH deploy step 2
        shell: bash
        run: |
          ssh -i /home/sandeep/goac-sandeep/goac-sandeep.pem ubuntu@ec2-13-232-52-59.ap-south-1.compute.amazonaws.com 'echo "Deployment completed."'
